services:
  - type: web
    name: tijzi-backend
    runtime: python3
    buildCommand: pip install --upgrade pip && pip install --only-binary=all -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ACCESS_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID 
        sync: false
      - key: TEMPLATE_NAME
        value: otp_login